# Dockerfile
FROM python:3.10-slim

RUN apt update && apt install -y iproute2 iputils-ping net-tools

WORKDIR /app

COPY roteador.py ./roteador.py
COPY topologia ./topologia

USER root

CMD ["python3", "-u", "/app/roteador.py", "0"]

